<a href="https://colab.research.google.com/github/himanshv22/KNN-Classification/blob/main/K_Nearest_Neighbors_(KNN)_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('Dataset.csv')
df.drop(columns=['User_ID'], inplace=True)
print(df)

    Gender  Age  EstimatedSalary  Purchased
0     Male   19            19000          0
1     Male   35            20000          0
2   Female   26            43000          0
3   Female   27            57000          0
4     Male   19            76000          0
5     Male   27            58000          0
6   Female   27            84000          0
7   Female   32           150000          1
8     Male   25            33000          0
9   Female   35            65000          0
10  Female   26            80000          0
11  Female   26            52000          0
12    Male   20            86000          0
13    Male   32            18000          0
14    Male   18            82000          0
15    Male   29            80000          0
16    Male   41            25000          1
17    Male   45            26000          1
18    Male   46            28000          1
19  Female   48            29000          1
20    Male   45            22000          1
21  Female   47            49000

In [2]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
print(df)
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

    Gender  Age  EstimatedSalary  Purchased
0        1   19            19000          0
1        1   35            20000          0
2        0   26            43000          0
3        0   27            57000          0
4        1   19            76000          0
5        1   27            58000          0
6        0   27            84000          0
7        0   32           150000          1
8        1   25            33000          0
9        0   35            65000          0
10       0   26            80000          0
11       0   26            52000          0
12       1   20            86000          0
13       1   32            18000          0
14       1   18            82000          0
15       1   29            80000          0
16       1   41            25000          1
17       1   45            26000          1
18       1   46            28000          1
19       0   48            29000          1
20       1   45            22000          1
21       0   47            49000

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=2)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[     1     45  22000]
 [     0     27  57000]
 [     0     26  80000]
 [     0     35  65000]
 [     1     19  76000]
 [     1     27  58000]
 [     1     41  25000]
 [     1     35  20000]
 [     0     26  43000]
 [     0     32 150000]
 [     1     46  28000]
 [     1     45  26000]
 [     0     26  52000]
 [     0     47  49000]
 [     1     32  18000]
 [     1     29  80000]
 [     1     25  33000]]
[[    1    20 86000]
 [    1    19 19000]
 [    1    18 82000]
 [    0    27 84000]
 [    0    48 29000]]
[1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0]
[0 0 0 0 1]


In [4]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.83666003  1.40162915 -0.93163816]
 [-1.19522861 -0.72163085  0.1595522 ]
 [-1.19522861 -0.83958974  0.87662016]
 [-1.19522861  0.22204026  0.40896714]
 [ 0.83666003 -1.66530196  0.75191269]
 [ 0.83666003 -0.72163085  0.19072907]
 [ 0.83666003  0.92979359 -0.83810756]
 [ 0.83666003  0.22204026 -0.99399189]
 [-1.19522861 -0.83958974 -0.27692394]
 [-1.19522861 -0.13183641  3.05900088]
 [ 0.83666003  1.51958804 -0.74457695]
 [ 0.83666003  1.40162915 -0.80693069]
 [-1.19522861 -0.83958974  0.00366787]
 [-1.19522861  1.63754693 -0.08986274]
 [ 0.83666003 -0.13183641 -1.05634563]
 [ 0.83666003 -0.48571307  0.87662016]
 [ 0.83666003 -0.95754863 -0.58869262]]
[[ 0.83666003 -1.54734307  1.06368136]
 [ 0.83666003 -1.66530196 -1.02516876]
 [ 0.83666003 -1.78326085  0.93897389]
 [-1.19522861 -0.72163085  1.00132763]
 [-1.19522861  1.75550582 -0.71340009]]


In [8]:
from collections import Counter
def euclidean_dist(x1,x2):
  return np.sqrt(np.sum((x1-x2)**2))

#k-NN algorithm
def knn(X_train, y_train, X_test, k=3):
  predictions=[]
  for test_point in X_test:
    #distances from test point to all training points
    distances=[euclidean_dist(test_point, x)for x in X_train]

    #find indices of the knn
    k_indices=np.argsort(distances)[:k]

    #get the labels of knn
    k_nearest_labels=[y_train[i] for i in k_indices]

    #determine the most common label
    most_common=Counter(k_nearest_labels).most_common(1)[0][0]
    predictions.append(most_common)

  return predictions

predictions=knn(X_train, y_train, X_test, k=5)
predictions = [int(p) for p in predictions]
print("Predictions are:", predictions)


Predictions are: [0, 0, 0, 0, 1]
